argument_specs:
  main:
    short_description: Common Variables
    description: []
    options:
      kubernetes_version:
        type: str
        required: true
        description: The Kubernetes version to install/upgrade.

      kubeadm_apiversion:
        type: str
        required: true
        description: The kubeadm configuration API version. For example 'v1beta3'.

      kubeadm_config_path:
        type: str
        default: /etc/kubernetes
        description: Where to store the kubeadm config file.

      kubeadm_patches_directory:
        type: str
        default: /etc/kubernetes/patches
        description: kubeadm components patches directory.

      kubeadm_certSANs:
        type: list
        default: []
        elements: str
        description: Add additional Subject Alternative Names (SANs) for the API server certificate.

      cluster_name:
        type: str
        description: The cluster name.
        default: kubernetes

      cluster_pod_cidr:
        type: str
        required: true
        description: The Pod network CIDR.

      cluster_service_cidr:
        type: str
        required: true
        description: The service network CIDR.

      cluster_dns_domain:
        type: str
        description: The cluster domain name.
        default: cluster.local

      cluster_apiserver_port:
        type: str
        description: The API server port (non-load-balanced).
        default: 6443

      control_plane_endpoint:
        type: str
        required: true
        description:
        - The control plane endpoint in the format 'LOAD_BALANCER_DNS:LOAD_BALANCER_PORT'.
        - See kubeadm documentation for more information.

      kubeadm_skip_phases:
        type: list
        default: []
        description: List of kubeadm init phases that will be skipped.

      control_plane_hostgroup:
        type: str
        required: true
        description: Inventory group name with all the control plane nodes.

      node_hostname:
        type: str
        default: inventory_hostname
        description:
          - To allow for a shorter inventory names, C(node_hostname) can be used to transform the short inventory name to a FQDN.
          - Typically, it will be defined in terms of C(inventory_hostname).
          - For example, I({{ node_hostname }}.example.com).
          - It's REQUIRED that the C(hostname) command outputs the same value as C(node_hostname) and that DNS resolves it to the host's IP.

      joined_control_plane_node:
        type: str
        default: 'First node in control_plane_hostgroup'
        description:
          - Some tasks require a control plane node to delegate to.
          - For example, joining a second control plane node, an existing control plane is needed to perform the join.
          - In such case, we use 'joined_control_plane_node' as the existing node.

      kubeadm_init_configuration:
        type: str
        description:
          - The kubeadm InitConfiguration object.
          - To override use C(kubeadm_init_configuration_override)

      kubeadm_init_configuration_override:
        type: str
        description:
         - Can be used to override part of the C(kubeadm_init_configuration) object.
         - A simple merge using the I(combine) filter.

      kubeadm_join_configuration:
        type: str
        description:
          - The kubeadm JoinConfiguration object.
          - To override use C(kubeadm_join_configuration_override)

      kubeadm_join_configuration_override:
        type: str
        description:
         - Can be used to override part of the C(kubeadm_join_configuration) object.
         - A simple merge using the I(combine) filter.

      kubeadm_cluster_configuration:
        type: str
        description:
          - The kubeadm ClusterConfiguration object.
          - To override use C(kubeadm_cluster_configuration_override)

      kubeadm_cluster_configuration_override:
        type: str
        description:
         - Can be used to override part of the C(kubeadm_cluster_configuration) object.
         - A simple merge using the I(combine) filter.

      kubeadm_kubelet_configuration:
        type: str
        description:
          - The kubeadm KubeletConfiguration object.
          - To override use C(kubeadm_kubelet_configuration_override)

      kubeadm_kubelet_configuration_override:
        type: str
        description:
         - Can be used to override part of the C(kubeadm_kubelet_configuration) object.
         - A simple merge using the I(combine) filter.
