- name: Ensure .cache/download
  file: 
    path: "~/.cache/download/"
    state: directory

- name: Ensure .cache/download_archives
  file: 
    path: "~/.cache/download_archives"
    state: directory

- vars:
    _checksum_url: "{{ download_url ~ checksum_file_suffix if checksum_file_suffix is defined else (checksum_file|default(None)) }}"
    checksum_available: "{{ _checksum_url is not none and checksum_algo is defined }}"
  block:
    - name: Ensure checksum
      get_url:
        url: "{{ _checksum_url }}"
        dest: "{{ download_dest }}"
      when: download_checksum_file and checksum_available

    - name: Enusre file
      get_url:
        url: "{{ download_url }}"
        checksum: "{{ omit if not (checksum_available or disable_checksum) else checksum_algo ~ ':' ~ (lookup('url', _checksum_url) if direct_checksum else _checksum_url) }}"
        dest: "{{ '~/.cache/download_archives/' if download_unarchive else download_dest }}"
        mode: "{{ file_mode }}"

- name: Unarchive file
  unarchive:
    src: "~/.cache/download_archives/{{ download_url | basename }}"
    dest: "~/.cache/download/"
    mode: '0700'
    remote_src: true
  when: download_unarchive

- name: Ensure file in archive at dest
  copy:
    src: "~/.cache/download/{{ download_file_in_archive }}"
    dest: "{{ download_dest }}"
    mode: "{{ file_mode }}"
    remote_src: true
  when: download_unarchive
