- name: Ensure .cache/download
  file: path={{ ansible_user_dir }}/.cache/download/ state=directory

- name: Ensure .cache/download_archives
  file: path={{ ansible_user_dir }}/.cache/download_archives state=directory


- name: Enusre file
  get_url:
    url: "{{ donwload_url }}"
    checksum: "{{ omit if _download_checksum is none or download_checksum_algo is undefined else
      download_checksum_algo ~ ':' ~  _download_checksum }}"
    dest: "{{ ansible_user_dir ~ '/.cache/download_archives/' if download_unarchive else download_dest }}"
    mode: "{{ file_mode }}"
  vars:
    _download_checksum: "{{ donwload_url ~ download_checksum_suffx if download_checksum_suffx is defined else (download_checksum|default(None)) }}"

- name: Unarchive file
  unarchive:
    src: "{{ ansible_user_dir }}/.cache/download_archives/{{ donwload_url | basename }}"
    dest: "{{ ansible_user_dir }}/.cache/download/"
    mode: '0700'
    remote_src: true
  when: download_unarchive

- name: Ensure file in archive at dest
  copy:
    src: "{{ ansible_user_dir }}/.cache/download/{{ download_file_in_archive }}"
    dest: "{{ download_dest }}"
    mode: "{{ file_mode }}"
    remote_src: true
  when: download_unarchive
# TODO BECOME