- name: Ensure .local/bin directory
  file:
    path: "~/.local/bin"
    state: directory
    mode: '0700'
    recurse: true

- include_tasks: download_file.yml
  vars:
    download_unarchive: false
    download_dest: "{{ download_only_path }}"
  when: download_only

- include_tasks: download_file.yml
  vars:
    download_dest: "{{ binary_path }}/{{ binary_name }}{{ '@' ~ binary_version if suffix_binary_with_version else '' }}"
  when: not download_only

- when: completion_command is defined and not download_only
  block:
    - name: Load completion script
      command: "{{ binary_path }}/{{ binary_name }}{{ '@' ~ binary_version if suffix_binary_with_version else '' }} {{ completion_command }}"
      changed_when: false
      register: completion_cmd_out

    - name: Ensure completion script
      copy:
        content: "{{ completion_cmd_out.stdout_lines | join('\n') }}"
        mode: '0644'
        dest: "{{ completion_path }}/{{ binary_name }}{{ '@' ~ binary_version if suffix_binary_with_version else '' }}"

