- include_tasks: download_binary.yml
  vars:
    donwload_url: >- 
      {{ github_base_url ~ '/' ~ github_project ~ '/releases/latest/download/' ~ github_file if github_version == 'latest'
        else github_base_url ~ '/' ~ github_project ~ '/releases/download/' ~ github_version ~ '/' ~ github_file }}
