- vars:
    github_path: >-
      {{ github_project ~ '/releases/latest/download' if release_version == 'latest'
          else github_project ~ '/releases/download/' ~ release_version ~ '/' }}
    download_url: "{{ github_base_url ~ '/' ~ github_path ~ '/' ~ release_file }}"
  block:
    - name: Enusre path when download_only  
      file: 
        path: "{{ download_only_path }}/{{ github_path }}"
        state: directory
      when: download_only and not download_only_flat
     

    - name: Download {{ release_file }} [{{ release_version }}] from {{ github_project }}
      include_tasks: download_file.yml
      vars:
        download_dest: "{{ download_only_path }}/{{ github_path }}"
        download_unarchive: false
      when: download_only and not download_only_flat


    - name: Download {{ release_file }} [{{ release_version }}] from {{ github_project }}
      include_tasks: download_file.yml
      vars:
        download_dest: "{{ binary_path }}/{{ binary_name }}"
      when: not download_only or download_only_flat

    - name: Load completion script
      command: "{{ binary_path }}/{{ binary_name }} {{ completion_command }}"
      changed_when: false
      register: completion_cmd_out
      when: completion_command is defined and not download_only

    - name: Ensure completion script in ~/.bash_completion
      blockinfile:
        path: "{{ ansible_user_dir }}/.bash_completion"
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ binary_name }}"
        create: true
        block: "{{ completion_cmd_out.stdout_lines | join('\n') }}"
      when: completion_command is defined and not download_only