- include_role: name=kubernetes.adm.reset
  when: kubeadm_reset and not is_control_plane

- include_tasks: join.yml
  when: k8s_nodes[inventory_hostname] is undefined

- when: is_control_plane
  block:
    - name: Ensure .kube directory
      file: path={{ ansible_user_dir }}/.kube state=directory
      
    - name: Ensure admin.conf is in the user's home directory
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ ansible_user_dir }}/.kube/config"
        remote_src: true
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0600'
      become: true

