dependencies:
  - role: kubernetes.adm.common

argument_specs:
  upgrade_crio:
    short_description: Upgrade CRI-O package
    description: []

  main:
    short_description: Upgrade Kubernetes
    description: 
      - Upgrade Kubernets control plane and worker nodes
      - "The phases are run in the sequence: 'facts', 'apply', 'node' and then 'kubelet'"
    options:
      phase:
        type: str
        required: true
        choices:
          - facts
          - apply
          - node
          - kubelet
        description:
          - Determines the kubeadm command/phase to run. 
          - "1) facts: Collect facts about the cluster. Must be run first."
          - "2) apply: Run 'kubeadm uprade apply' on one of the control plane nodes."
          - "3) node: Run 'kubeadm uprade node'."
          - "4) kubelet: Drain the node and upgrades the Kubelet."
          - Consult the kubeadm documentation for more information.

      pre_kubelet_upgrade_hook:
        type: str
        description: A tasks file to execute before upgrading the kubelet.