- name: Enusre bash-completion
  yum: name=bash-completion state=present
  become: true

- name: Load kubectl completion script
  command: kubectl completion bash
  changed_when: false
  register: kubectl_completion

- name: Ensure kubectl completion in /etc/bash_completion.d
  copy:
    content: "{{ kubectl_completion.stdout_lines | join('\n') }}"
    dest: /etc/bash_completion.d/kubectl
    mode: '0644'

  become: true

- name: Ensure kubectl aliases
  copy:
    src: kubectl_aliases
    dest: /etc/profile.d/kubectl_aliases.sh
    mode: '0644'

  become: true
  when: kubectl_aliases

- name: Ensure complete_alias
  copy:
    src: complete_alias
    dest: /etc/bash_completion.d/complete_alias
    mode: '0644'

  become: true
  when: complete_alias

- when: kubens_command
  become: true
  block:
    - name: Ensure kubens alias
      copy:
        content: |
          #!/bin/bash
          kubectl config set-context --current --namespace "$@"

        dest: /usr/local/bin/kubens
        mode: '0755'

    - name: Ensure completion for kubens
      copy:
        content: |
          # bash completion for 'kubens'
          _kubens_completions()
          {
          if [ "${#COMP_WORDS[@]}" != "2" ]; then
              return
          fi
          COMPREPLY=($(compgen -W "$(kubectl get ns -o custom-columns='NAME:.metadata.name' --no-headers)" -- "${COMP_WORDS[1]}"))
          }

          complete -F _kubens_completions kubens

        mode: '0644'
        dest: /etc/bash_completion.d/kubens
