- name: Enusre bash-completion
  yum: name=bash-completion state=present
  become: true

- name: Load kubectl completion script
  command: kubectl completion bash 
  changed_when: false
  register: kubectl_completion

- name: Ensure kubectl completion in /etc/bash_completion.d
  copy:
    content: "{{ kubectl_completion.stdout_lines | join('\n') }}"
    dest: /etc/bash_completion.d/kubectl
  
  become: true

- name: Ensure k alias
  copy:
    content: |
      alias k=kubectl && complete -F __start_kubectl k
      
    dest: /etc/profile.d/k_alias.sh
    
  become: true

- name: Ensure kubens alias
  copy:
    content: |
      alias kubens='kubectl config set-context --current --namespace '
      
    dest: /etc/profile.d/kubens_alias.sh
    
  become: true


- name: Ensure completion for kubens
  copy:
    src: kubens.sh
    dest: /etc/bash_completion.d/kubens
  
  become: true

- name: Ensure correct mode on kubectl completions
  file:
    path: /etc/bash_completion.d/kubectl
    mode: '0644'

  become: true