# Contract: After running the info_tasks the following MUST be set:
# current_kubelet_version
# current_crio_version
# If there are no existing installtions the value is set to an empty string

- name: YUM info kubelet
  yum: list=kubelet
  register: yum_kubelet_out
  become: true

- name: YUM info cri-o
  yum: list=cri-o
  register: yum_crio_out
  become: true

- vars:
    _kubelet_info: "{{ yum_kubelet_out.results | selectattr('yumstate', 'eq', 'installed') }}"
    _crio_info: "{{ yum_crio_out.results | selectattr('yumstate', 'eq', 'installed') }}"
  set_fact:
    current_crio_version: "{{ _crio_info[0].version if (_crio_info | length > 0) else '' }}"
    current_kubelet_version: "{{ _kubelet_info[0].version if (_kubelet_info | length > 0) else '' }}"
