---
- include_tasks: "{{ swap_tasks }}"

- include_tasks: "{{ cni_tasks }}"

- include_tasks: "{{ cri_tasks }}"

- include_tasks: "{{ install_kube_tasks }}"

- name: Ensure patches directory
  file:
    path: "{{ kubeadm_patches_directory }}"
    state: directory

  become: true

- name: Patch control plane SELinux type label
  copy:
    dest: "{{ kubeadm_patches_directory }}/{{ item }}SELinux.yaml"
    content: |
      spec:
        securityContext:
          seLinuxOptions:
            type: spc_t
  become: true
  when: is_control_plane
  loop:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - etcd

- name: Ensure kernel parameters are relaoded
  command: sysctl -p
  become: true

- name: Ensure kubelet.service is enabled
  systemd:
    name: kubelet.service
    enabled: true
    daemon_reload: true

  become: true

- name: Ensure bash completion
  include_tasks: "{{ completion_tasks }}"
  when: is_control_plane