---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
# We don't need bootstrap-token, but if we skip we get into https://github.com/kubernetes-sigs/kubespray/issues/4117
skipPhases: {{ ['upload-certs'] + kubeadm_skip_phases }}
nodeRegistration:
  taints: null
patches:
  directory: {{ kubeadm_patches_directory }}
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration

controlPlaneEndpoint: {{ control_plane_endpoint }}
clusterName: {{ cluster_name }}
kubernetesVersion: {{ kubernetes_version }}

networking:
  podSubnet: {{ cluster_pod_cidr }}
  serviceSubnet: {{ cluster_service_cidr }}
  dnsDomain: {{ cluster_dns_domain }}

apiServer: {}
controllerManager: {}
scheduler: {}
