argument_specs:
  download_file:
    short_description: Download file
    description:
      - Download file from the URL C(download_url).
      - When C(download_unarchive) is true, the downloaded file will be unarchived.
    options:
      download_base_url:
        type: str
        description: 
          - The base download URL.
          - Useful when syncing files to an offline destination.
      download_url:
        type: str
        required: true
        description: 
          - The file URL.
          - Should always be defined with C(download_base_url) in mind.
          - For example {{ download_base_url | default('https://abc.com/my/folder') }}/file.tar.gz
      download_unarchive:
        type: bool
        description: 
          - Whether the downloaded file will be unarchived.
          - True when C(download_file_in_archive) is defined
      download_file_in_archive:
        type: str
        description:
          - The file inside the archive that will be copied to C(download_dest).
          - Required when C(download_unarchive).
      download_dest:
        type: str
        required: true
        description: The download destination.
      file_mode:
        type: str
        default: '0700'
        description: The file mode.
      checksum_file:
        type: str
        description: 
          - The URL to a file containg the digest.
          - Mutually exclusive with C(checksum_file_suffix).
          - See C(get_url) module for more info.
      checksum_file_suffix:
        type: str
        description: 
          - The suffix that will be appended to C(download_url) to construct the checksum URL.
          - Mutually exclusive with C(checksum_file).
      checksum_algo:
        type: str
        description: The checksum algorithm.
      direct_checksum:
        type: bool
        default: false
        description: 
        - Set to true when checksum file contains only the digest.
        - Work around for https://github.com/ansible/ansible/issues/54390.
      disable_checksum:
        type: bool
        default: false
        description:  Disable checksum verification.
      download_checksum_file:
        type: bool
        default: false
        description: When true, the checksum file will be downloaded along side the downloaded file.
        

  download_binary:
    short_description: Download and install a binary file
    description: []
    options:
      binary_path:
        type: str
        default: "~/.local/bin"
        description: The directory to store binary files.
      binary_name:
        type: str
        required: true
        description: The final name for the binary file.
      download_only:
        type: bool
        default: false
        description:
          - When true no unarchiving is done, and the file is downloaded to C(download_only_path).
      download_only_path:
        type: str
        description: The path to store files when C(download_only) is true
      completion_command:
        type: str
        description: 
          - The shell completion command.
          - The expression {{ ansible_user_shell | basename }} can be used to determine the user's shell.


  gh_binary:
    short_description: Download and install a binary file from Github
    description:
      - Download a file from the release page in a Github project.
      - Using the same URL structure used by Github, the C(github_base_url) can point to a private location.
      - All checksum related variables in C(download_file) are available.
    options:
      github_base_url:
        type: str
        default: "https://github.com"
        description: The base download URL.
      github_project:
        type: str
        required: true
        description: The orginization/project names.
      release_version:
        type: str
        required: true
        description: The release version.   
      release_file:
        type: str
        required: true
        description: The file to download.
      download_only:
        type: bool
        default: false
        description:
          - When true no unarchiving is done, and the file is downloaded to C(download_only_path).
      download_only_path:
        type: str
        description: The path to store files when C(download_only) is true
      download_only_flat:
        type: bool
        default: false
        description: 
          - When false, store files under {{ download_only_path ~ '/' ~ github_project ~ '/releases/download/' ~ release_version }}
          - Mimics the Github URL for the file.
          - When true, store files under C(download_only_path)
      completion_command:
        type: str
        description: 
          - The shell completion command.
          - The expression {{ ansible_user_shell | basename }} can be used to determine the user shell.
