dependencies:
  - role: kubernetes.adm.common

argument_specs:
  main:
    short_description: Prepare node for Kubernetes installtion
    description:
      - Ensure that the node has the desired swap state, kernel modules and kernel parameters.
      - Configure the required repositories for the container runtime and Kubernetes.
      - Install the container runtime.
      - Install Kubernetes packages
      - Install C(kubernetes.core) and its requirements on control plane nodes.

    options:
      cri:
        type: str
        default: containerd
        choices: [containerd, cri-o]
        description:
          - The container runtime.

      swap_state:
        type: str
        default: disabled
        choices: [enabled, disabled]
        description:
          - Whether to disable or enable swap.
          - Attempts to undo a previous execution of I(swap_state=disabled) will not create a new swap partition or file.

      swap_tasks:
        type: str
        default: _swap.yml
        description: Tasks file for swap memory.

      cni_tasks:
        type: str
        default: _cni.yml
        description: Tasks file for preparing the OS for CNI.

      cri_tasks:
        type: str
        description: Tasks file for preparing and installing the container runtime.

      no_yum_repo:
        type: bool
        default: false
        description: When true, no YUM reposioiry will be added.

      completion_tasks:
        type: str
        default: _completion.yml
        description: Tasks file for installing shell completion.

      kubectl_aliases:
        type: bool
        default: true
        description: Add kubectl aliases from github.com/ahmetb/kubectl-aliases

      complete_alias:
        type: bool
        default: true
        description: Add complete_alias from github.com/cykerway/complete-alias

      kubens_command:
        type: bool
        default: true
        description: Add kubens shell script to switch between namespaces.

      prepare_upgrade:
        type: bool
        default: false
        description:
          - Only relevent if there is an existing installtion of the CR or Kubernetes packages.
          - When true, the CR and Kubernetes will upgraded/downgraded to C({{ kubernetes_version }}).
          - Should only by used when initializing a new cluster.

      containerd_version:
        type: str
        description:
          - The containerd package version.

      crio_version:
        type: str
        default: Kubernetes MAJOR.MINOR from kubernetes_version
        description: The CRI-O version to install/upgrade.

      crio_os:
        type: str
        description: Used in setting up the CRI-O YUM repository. On CentOS 8 it would be 'CentOS_8'.