---
# defaults file for prepare
cri: containerd

swap_tasks: _swap.yml

cni_tasks: _cni.yml

cri_tasks: "{{ '_containerd.yml' if cri == 'containerd' else '_crio.yml' }}"

install_kube_tasks: _install_kube.yml

completion_tasks: _completion.yml

swap_state: disabled
no_yum_repo: false
prepare_upgrade: false
kubectl_aliases: true
complete_alias: true
kubens_command: true

crio_version: "{{ kubernetes_version.split('.')[0:2] | join('.') }}"
crio_os: "CentOS_{{ ansible_distribution_major_version }}{{ '_Stream' if ansible_distribution_release == 'Stream' }}"

python_package: "{{ 'python36' if ansible_distribution_major_version == '8' else 'python3' }}"