- assert:
    that: ('v' + kubernetes_version) in control_plane_versions.values()
    fail_msg: No control plane node with {{ kubernetes_version }}. Did you run the apply phase?
    quiet: true

- when:  ('v' + kubernetes_version) is version(k8s_nodes[node_hostname].kubeletVersion, '>')
  block:
    - name: Ensure node is drained
      kubernetes.core.k8s_drain:
        name: "{{ node_hostname }}"
        state: drain
        delete_options:
          ignore_daemonsets: true
          delete_emptydir_data: true
      delegate_to: "{{ joined_control_plane_node }}"

    - include_tasks: "{{ pre_kubelet_upgrade_hook }}"
      when: pre_kubelet_upgrade_hook is defined and pre_kubelet_upgrade_hook is not none

    - include_tasks: "{{ update_kube_tasks }}"


- name: Ensure node is schedulable
  kubernetes.core.k8s_drain:
    name: "{{ node_hostname }}"
    state: uncordon
  delegate_to: "{{ joined_control_plane_node }}"