github_project: projectcalico/calicoctl
github_version: "{{ calicoctl_version | default('latest') }}"
github_file: calicoctl-linux-{{ arch }}
binary_file: calicoctl

download_mode: download_gh
arch_map: "{{ go_arch_map }}"