github_project: cilium/cilium-cli
release_version: "{{ 'v' ~ binary_version if binary_version else 'latest' }}"
binary_version: "{{ cilium_cli_version | default(None) }}"
release_file: cilium-linux-{{ arch }}.tar.gz
download_file_in_archive: cilium
binary_name: cilium
checksum_file_suffix: '.sha256sum'
checksum_algo: 'sha256'
completion_command: completion {{  ansible_user_shell | basename }}
download_mode: gh_binary
arch_lang: go