github_project: jetstack/cert-manager
release_version: "{{ 'v' ~ cmctl_version if cmctl_version else 'latest' }}"
release_version: "{{ cmctl_version | default(None) }}"
release_file: cmctl-linux-amd64.tar.gz
download_file_in_archive: cmctl
binary_name: cmctl
completion_command: completion {{  ansible_user_shell | basename }}
download_mode: gh_binary
arch_lang: go