github_project: jetstack/cert-manager
release_version: "{{ cmctl_version | default('latest') }}"
release_file: cmctl-linux-amd64.tar.gz
binary_file: cmctl
completion_command: completion {{  ansible_user_shell | basename }}
download_unarchive: true

download_mode: download_gh
arch_map: "{{ go_arch_map }}"
