github_project: jetstack/cert-manager
release_version: "{{ cmctl_version | default('latest') }}"
release_file: cmctl-linux-amd64.tar.gz
download_file_in_archive: cmctl
binary_name: cmctl
completion_command: completion {{  ansible_user_shell | basename }}
download_mode: download_gh
arch_map: "{{ go_arch_map }}"
