download_url: "{{ helm_base_url | default('https://get.helm.sh', true) }}/helm-v{{ helm_version }}-linux-{{ arch }}.tar.gz"
download_file_in_archive: linux-{{ arch }}/helm
binary_name: helm
checksum_file_suffix: '.sha256sum'
checksum_algo: 'sha256'
completion_command: completion {{  ansible_user_shell | basename }}
download_mode: download_binary
arch_lang: go