github_project: cilium/hubble
release_version: "{{ hubble_version | default('latest') }}"
release_file: hubble-linux-{{ arch }}.tar.gz
download_file_in_archive: hubble
binary_name: hubble
checksum_file_suffix: '.sha256sum'
checksum_algo: 'sha256'
completion_command: completion {{  ansible_user_shell | basename }}
download_mode: download_gh
arch_map: "{{ go_arch_map }}"