download_url: "{{ kubectl_base_url | default('https://dl.k8s.io/release') }}/{{ kubectl_version }}/bin/linux/{{ arch }}/kubectl"
binary_name: kubectl
checksum_file_suffix: .sha256
checksum_algo: sha256
completion_command: completion {{  ansible_user_shell | basename }}
download_mode: download_binary
direct_checksum: true
arch_lang: go