github_project: kubernetes-sigs/kubebuilder
release_version: "{{ 'v' ~ binary_version if binary_version else 'latest' }}"
binary_version: "{{ kubebuilder_version | default(None) }}"
release_file:  kubebuilder_linux_{{ arch }}
binary_name: kubebuilder
checksum_file: "{{ download_url | dirname }}/checksums.txt"
checksum_algo: sha256
completion_command: completion {{  ansible_user_shell | basename }}
download_mode: gh_binary
arch_lang: go