github_project: linkerd/linkerd2
release_version: stable-{{ binary_version }}
binary_version: "{{ linkerd_version }}"
release_file:  linkerd2-cli-stable-{{ binary_version}}-linux-{{ arch }}
checksum_file_suffix: .sha256
checksum_algo: sha256
binary_name: linkerd
completion_command: completion {{  ansible_user_shell | basename }}
download_mode: gh_binary
arch_lang: go