github_project: operator-framework/operator-sdk
release_version: "{{ operator_sdk_version | default('latest') }}"
release_file:  operator-sdk_linux_{{ arch }}
checksum_file: "{{ download_url | dirname }}/checksums.txt"
checksum_algo: sha256
binary_name: operator-sdk
completion_command: completion {{  ansible_user_shell | basename }}
download_mode: gh_binary
arch_lang: go