github_project: starship/starship
release_version: "{{ starship_version | default('latest') }}"
release_file:  starship-{{ arch }}-unknown-linux-gnu.tar.gz 
binary_file: starship
download_unarchive: true

download_mode: download_gh
arch_map: "{{ rust_arch_map }}"