github_project: smallstep/cli
release_version: v{{ binary_version }}
release_file: step_linux_{{ binary_version }}_{{ arch }}.tar.gz
download_file_in_archive: step_{{ binary_version }}/bin/step
binary_name: step
binary_version: "{{ step_cli_version }}"
completion_command: completion {{  ansible_user_shell | basename }}
checksum_file: "{{ download_url | dirname }}/checksums.txt"
checksum_algo: 'sha256'
download_mode: gh_binary
arch_lang: go