github_project: smallstep/certificates
release_version: "{{ step_ca_version }}"
release_file: step-ca_linux_{{ step_ca_version[1:] }}_{{ arch }}.tar.gz
download_file_in_archive: step-ca_{{ step_ca_version[1:] }}/bin/step-ca
binary_name: step-ca
checksum_file: "{{ download_url | dirname }}/checksums.txt"
checksum_algo: 'sha256'
download_mode: gh_binary
arch_lang: go