download_unarchive: "{{ download_file_in_archive is defined and download_file_in_archive is not none }}"
file_mode: "{{ '0755' if system_wide else '0700' }}"

# https://github.com/ansible/ansible/issues/54390
direct_checksum: false

github_base_url: https://github.com

system_wide: false

binary_path: "{{ system_binary_path if system_wide else user_binary_path }}"

user_binary_path: "~/.local/bin"
system_binary_path: "/usr/local/bin"

completion_path: "{{ system_completion_path if system_wide else user_completion_path }}"

user_completion_path: "~/.local/share/bash-completion/completions"
system_completion_path: "/etc/bash_completion.d"

download_only: false
download_only_flat: false
download_checksum_file: false
disable_checksum: false
# download_only_path: ''

suffix_binary_with_version: false

arch_lang_map:
  go:
    x86_64: amd64
    arm64: arm64
  rust:
    x86_64: x86_64
    arm64: aarch64

arch_map: "{{ arch_lang_map[arch_lang] }}"

arch: "{{ arch_map[ansible_architecture] }}"

# arch_lang: go

update_alternatives: false