download_unarchive: "{{ download_file_in_archive is defined and download_file_in_archive is not none }}"
file_mode: '0700'
github_base_url: https://github.com

binary_path: "{{ ansible_user_dir }}/.local/bin"

download_only: false
download_only_flat: false
download_checksum_file: false
disable_checksum: false
# download_only_path: ''

go_arch_map:
  x86_64: amd64
  arm64: arm64

rust_arch_map:
  x86_64: x86_64
  arm64: aarch64

arch: "{{ arch_map[ansible_architecture] }}"

arch_map: "{{ go_arch_map }}"
