download_unarchive: "{{ download_file_in_archive is defined and download_file_in_archive is not none }}"
file_mode: '0700'

# https://github.com/ansible/ansible/issues/54390
direct_checksum: false

github_base_url: https://github.com

binary_path: "{{ ansible_user_dir }}/.local/bin"

download_only: false
download_only_flat: false
download_checksum_file: false
disable_checksum: false
# download_only_path: ''

arch_map:
  go:
    x86_64: amd64
    arm64: arm64
  rust:
    x86_64: x86_64
    arm64: aarch64

arch: "{{ arch_map[arch_lang][ansible_architecture] }}"

arch_lang: go
