argument_specs:
  main:
    short_description: Setup HA Floating IP Using Keepalived
    description:
      - Based on L(Software load balancing,https://github.com/kubernetes/kubeadm/blob/main/docs/ha-considerations.md#options-for-software-load-balancing).
      - Keepalived requires that all nodes are in the same subnet(broadcast domain).
    options:
      keepalived_master:
        type: str
        required: true
        description: The server with the MASTER state in C(keepalived.conf). Must be an inventory host.
      
      keepalived_interface:
        type: str
        required: true
        description: The network interface used by keepalived VRRP protocol. For exmaple eth0.

      keepalived_vip:
        type: str
        required: true
        description:
          - The keepalived VIP

      keepalived_router_id:
        type: int
        required: true
        description:
        - The VRRP instance router id.
        - Should be unique among different instances of VRRP.
        - See man:keepalived.conf(5) for more info.

      keepalived_check_script_template:
        type: str
        required: true
        description:
          - The health check script template that will be used by keepalived.

      keepalived_peers:
        type: dict
        required: true
        description:
          - Key value pairs of inventory hosts and their IPs.