- name: Ensure kubeadm.conf using {{ kubeadm_config_template }} template
  template:
    src: "{{ kubeadm_config_template }}"
    dest: "{{ kubeadm_config_path }}/kubeadm.conf"
  
  become: true

- name: kubeadm init
  command: kubeadm init --config "{{ kubeadm_config_path }}/kubeadm.conf" --skip-certificate-key-print --skip-token-print

  become: true
  register: kubeadm_out

- debug: msg={{ kubeadm_out.stdout_lines | join('\n') }}

- set_fact:
    k8s_new_joiner: true